package one.launay.deckswipe.ui.strings

data class Strings(
    val floatingSettingsA11y: String,
    val navHome: String,
    val navSettings: String,
    val navDecks: String,
    val navCards: String,
    val fabCreateDeck: String,
    val settingsTitle: String,
    val languageLabel: String,
    val themeLabel: String,
    val languageEnglish: String,
    val languageFrench: String,
    val themeLight: String,
    val themeDark: String,
    val homeCreateDeckTitle: String,
    val homeAiGeneratedTitle: String,
    val homeAiGeneratedDescription: String,
    val homeAiGeneratedButton: String,
    val homeManualTitle: String,
    val homeManualDescription: String,
    val homeManualButton: String,
    val homeImportTitle: String,
    val homeImportDescription: String,
    val homeImportButton: String,
    val homeDashboardTitle: String,
    val homeRecentDeckTitle: String,
    val homeStatsTitle: String,
    val homeSuggestionsTitle: String,
    val homeNoRecentDeck: String,
    val homeNoSuggestions: String,
    val homeTotalDecksLabel: String,
    val homeTotalDueCardsLabel: String,
    val homeLoadError: String,
    val homeBrowseDecksLink: String,
    val deckListTitle: String,
    val deckListCreateDeck: String,
    val deckListRetry: String,
    val deckListLoadError: String,
    val deckListEmptyTitle: String,
    val deckListEmptySubtitle: String,
    val deckEditorTitle: String,
    val deckEditorDeckName: String,
    val deckEditorTags: String,
    val deckEditorCardsSection: String,
    val deckEditorFront: String,
    val deckEditorBack: String,
    val deckEditorHint: String,
    val deckEditorRemoveCard: String,
    val deckEditorAddCard: String,
    val deckEditorCancel: String,
    val deckEditorSave: String,
    val deckEditorErrorEmptyName: String,
    val deckEditorErrorNoCards: String,
    val studyTitle: String,
    val studyLoading: String,
    val studyDoneTitle: String,
    val studyDoneSubtitle: String,
    val studyDoneBack: String,
    val studyUntitledDeck: String,
    val studyRemaining: String,
    val studySessionReviewed: String,
    val studyFlipCard: String,
    val studyShowQuestion: String,
    val studyHintLabel: String,
    val studySwipeHint: String,
    val importIntro: String,
    val importCopyPrompt: String,
    val importFromClipboard: String,
    val importCancel: String,
    val importErrorClipboardEmpty: String,
    val importErrorNotText: String,
    val importErrorTextEmpty: String,
    val importErrorInvalidJson: String,
    val importErrorMissingFields: String,
    val placeholderAllCards: String,
    val deckEditorTitleEdit: String,
    val deckFavoriteA11y: String,
    val deckDetailsLearn: String,
    val deckDetailsEditDeck: String,
    val deckDetailsEditTitle: String,
    val deckDetailsDescription: String,
    val deckDetailsNoDescription: String,
    val deckDetailsTags: String,
    val deckDetailsChangeCover: String,
    val deckDetailsRemoveCover: String,
    val deckDetailsSave: String,
    val deckDetailsMastery: String,
    val deckDetailsCardsCount: String,
    val deckDetailsDueCount: String,
    val deckDetailsLoadError: String,
    val deckDetailsTitleHint: String,
    val deckDetailsDescHint: String,
    val deckDetailsTagsHint: String,
    val commonOk: String,
    val commonCancel: String
)

val StringsEn = Strings(
    floatingSettingsA11y = "Settings",
    navHome = "Home",
    navSettings = "Settings",
    navDecks = "Decks",
    navCards = "Cards",
    fabCreateDeck = "Create a deck",
    settingsTitle = "Settings",
    languageLabel = "Language",
    themeLabel = "Color scheme",
    languageEnglish = "English",
    languageFrench = "French",
    themeLight = "Light",
    themeDark = "Dark",
    homeCreateDeckTitle = "Create a deck",
    homeAiGeneratedTitle = "AI create & import",
    homeAiGeneratedDescription = "Enter a prompt and an amount of cards and see the magic happen.",
    homeAiGeneratedButton = "Create an AI deck",
    homeManualTitle = "Create own cards",
    homeManualDescription = "Make your own flashcards manually.",
    homeManualButton = "Create cards",
    homeImportTitle = "Import deck",
    homeImportDescription = "Paste cards from the clipboard or another source.",
    homeImportButton = "Import cards",
    homeDashboardTitle = "Welcome back",
    homeRecentDeckTitle = "Recent deck",
    homeStatsTitle = "Statistics",
    homeSuggestionsTitle = "Time to review",
    homeNoRecentDeck = "You have not created any decks yet.",
    homeNoSuggestions = "Nothing to review right now.",
    homeTotalDecksLabel = "Total decks",
    homeTotalDueCardsLabel = "Cards due",
    homeLoadError = "Failed to load home data.",
    homeBrowseDecksLink = "Browse all decks",
    deckListTitle = "Your decks",
    deckListCreateDeck = "Create deck",
    deckListRetry = "Retry",
    deckListLoadError = "Failed to load decks.",
    deckListEmptyTitle = "No decks yet.",
    deckListEmptySubtitle = "Create a new deck manually or import one from your favorite AI.",
    deckEditorTitle = "New deck",
    deckEditorDeckName = "Deck name",
    deckEditorTags = "Tags (comma-separated, optional)",
    deckEditorCardsSection = "Cards",
    deckEditorFront = "Front",
    deckEditorBack = "Back",
    deckEditorHint = "Hint (optional)",
    deckEditorRemoveCard = "Remove card",
    deckEditorAddCard = "Add card",
    deckEditorCancel = "Cancel",
    deckEditorSave = "Save deck",
    deckEditorErrorEmptyName = "Deck name cannot be empty.",
    deckEditorErrorNoCards = "Add at least one card with front and back.",
    studyTitle = "Study",
    studyLoading = "Loading cards...",
    studyDoneTitle = "You are done for now.",
    studyDoneSubtitle = "There are no cards due in this deck.",
    studyDoneBack = "Back",
    studyUntitledDeck = "Deck",
    studyRemaining = "Remaining",
    studySessionReviewed = "Reviewed this session",
    studyFlipCard = "Flip card",
    studyShowQuestion = "Show question",
    studyHintLabel = "Hint",
    studySwipeHint = "Swipe left if you forgot, swipe right if you knew it.",
    importIntro = "You can generate decks with your favorite AI or paste JSON you prepared yourself. Your data never leaves this device.",
    importCopyPrompt = "Copy AI prompt to clipboard",
    importFromClipboard = "Import from clipboard",
    importCancel = "Cancel",
    importErrorClipboardEmpty = "Clipboard is empty.",
    importErrorNotText = "Clipboard does not contain text.",
    importErrorTextEmpty = "Clipboard text is empty.",
    importErrorInvalidJson = "Clipboard text is not valid JSON.",
    importErrorMissingFields = "JSON is missing required fields.",
    placeholderAllCards = "All cards (coming soon)",
    deckEditorTitleEdit = "Edit deck",
    deckFavoriteA11y = "Favorite",
    deckDetailsLearn = "Learn deck",
    deckDetailsEditDeck = "Edit cards",
    deckDetailsEditTitle = "Edit title",
    deckDetailsDescription = "Description",
    deckDetailsNoDescription = "No description yet.",
    deckDetailsTags = "Tags",
    deckDetailsChangeCover = "Change cover",
    deckDetailsRemoveCover = "Remove cover",
    deckDetailsSave = "Save",
    deckDetailsMastery = "Known",
    deckDetailsCardsCount = "Cards",
    deckDetailsDueCount = "Due now",
    deckDetailsLoadError = "Could not load this deck.",
    deckDetailsTitleHint = "Deck title",
    deckDetailsDescHint = "Short description",
    deckDetailsTagsHint = "tag1, tag2",
    commonOk = "OK",
    commonCancel = "Cancel"
)

val StringsFr = Strings(
    floatingSettingsA11y = "Réglages",
    navHome = "Accueil",
    navSettings = "Réglages",
    navDecks = "Paquets",
    navCards = "Cartes",
    fabCreateDeck = "Créer un paquet",
    settingsTitle = "Réglages",
    languageLabel = "Langue",
    themeLabel = "Schéma de couleurs",
    languageEnglish = "Anglais",
    languageFrench = "Français",
    themeLight = "Clair",
    themeDark = "Sombre",
    homeCreateDeckTitle = "Créer un paquet",
    homeAiGeneratedTitle = "Création et import IA",
    homeAiGeneratedDescription = "Entrez une consigne et un nombre de cartes et laissez la magie opérer.",
    homeAiGeneratedButton = "Créer un paquet IA",
    homeManualTitle = "Créer vos cartes",
    homeManualDescription = "Créez vos propres fiches manuellement.",
    homeManualButton = "Créer des cartes",
    homeImportTitle = "Importer un paquet",
    homeImportDescription = "Collez des cartes depuis le presse-papiers ou une autre source.",
    homeImportButton = "Importer des cartes",
    homeDashboardTitle = "Bon retour",
    homeRecentDeckTitle = "Paquet récent",
    homeStatsTitle = "Statistiques",
    homeSuggestionsTitle = "A revoir",
    homeNoRecentDeck = "Vous n'avez pas encore créé de paquet.",
    homeNoSuggestions = "Rien à réviser pour le moment.",
    homeTotalDecksLabel = "Nombre de paquets",
    homeTotalDueCardsLabel = "Cartes dues",
    homeLoadError = "Impossible de charger l'accueil.",
    homeBrowseDecksLink = "Voir tous les paquets",
    deckListTitle = "Vos paquets",
    deckListCreateDeck = "Créer un paquet",
    deckListRetry = "Réessayer",
    deckListLoadError = "Impossible de charger les paquets.",
    deckListEmptyTitle = "Aucun paquet pour le moment.",
    deckListEmptySubtitle = "Créez un paquet manuellement ou importez-en un depuis votre IA preferee.",
    deckEditorTitle = "Nouveau paquet",
    deckEditorDeckName = "Nom du paquet",
    deckEditorTags = "Etiquettes (séparées par des virgules, optionnel)",
    deckEditorCardsSection = "Cartes",
    deckEditorFront = "Recto",
    deckEditorBack = "Verso",
    deckEditorHint = "Indice (optionnel)",
    deckEditorRemoveCard = "Retirer la carte",
    deckEditorAddCard = "Ajouter une carte",
    deckEditorCancel = "Annuler",
    deckEditorSave = "Enregistrer",
    deckEditorErrorEmptyName = "Le nom du paquet ne peut pas etre vide.",
    deckEditorErrorNoCards = "Ajoutez au moins une carte avec recto et verso.",
    studyTitle = "Révision",
    studyLoading = "Chargement des cartes...",
    studyDoneTitle = "C'est tout pour le moment.",
    studyDoneSubtitle = "Il n'y a aucune carte due dans ce paquet.",
    studyDoneBack = "Retour",
    studyUntitledDeck = "Paquet",
    studyRemaining = "Restantes",
    studySessionReviewed = "Revues cette session",
    studyFlipCard = "Retourner",
    studyShowQuestion = "Voir la question",
    studyHintLabel = "Indice",
    studySwipeHint = "Glissez a gauche si vous avez oublie, a droite si vous saviez.",
    importIntro = "Vous pouvez generer des paquets avec votre IA preferee ou coller du JSON que vous avez prepare. Vos donnees ne quittent jamais cet appareil.",
    importCopyPrompt = "Copier la consigne IA dans le presse-papiers",
    importFromClipboard = "Importer depuis le presse-papiers",
    importCancel = "Annuler",
    importErrorClipboardEmpty = "Le presse-papiers est vide.",
    importErrorNotText = "Le presse-papiers ne contient pas de texte.",
    importErrorTextEmpty = "Le texte du presse-papiers est vide.",
    importErrorInvalidJson = "Le texte du presse-papiers n'est pas du JSON valide.",
    importErrorMissingFields = "Le JSON ne contient pas les champs requis.",
    placeholderAllCards = "Toutes les cartes (bientot)",
    deckEditorTitleEdit = "Modifier le paquet",
    deckFavoriteA11y = "Favori",
    deckDetailsLearn = "Reviser le paquet",
    deckDetailsEditDeck = "Modifier les cartes",
    deckDetailsEditTitle = "Modifier le titre",
    deckDetailsDescription = "Description",
    deckDetailsNoDescription = "Pas encore de description.",
    deckDetailsTags = "Etiquettes",
    deckDetailsChangeCover = "Changer la couverture",
    deckDetailsRemoveCover = "Retirer la couverture",
    deckDetailsSave = "Enregistrer",
    deckDetailsMastery = "Connu",
    deckDetailsCardsCount = "Cartes",
    deckDetailsDueCount = "A revoir",
    deckDetailsLoadError = "Impossible de charger ce paquet.",
    deckDetailsTitleHint = "Titre du paquet",
    deckDetailsDescHint = "Courte description",
    deckDetailsTagsHint = "etiquette1, etiquette2",
    commonOk = "OK",
    commonCancel = "Annuler"
)
