package one.launay.deckswipe.ui.strings

data class Strings(
    val navHome: String,
    val navSettings: String,
    val navDecks: String,
    val navCards: String,
    val navBrowse: String,
    val navAnalytics: String,
    val settingsTitle: String,
    val languageLabel: String,
    val themeLabel: String,
    val languageEnglish: String,
    val languageFrench: String,
    val themeLight: String,
    val themeDark: String,
    val homeCreateDeckTitle: String,
    val homeAiGeneratedTitle: String,
    val homeAiGeneratedDescription: String,
    val homeAiGeneratedButton: String,
    val homeManualTitle: String,
    val homeManualDescription: String,
    val homeManualButton: String,
    val homeImportTitle: String,
    val homeImportDescription: String,
    val homeImportButton: String,
    val homeDashboardTitle: String,
    val homeRecentDeckTitle: String,
    val homeStatsTitle: String,
    val homeSuggestionsTitle: String,
    val homeNoRecentDeck: String,
    val homeNoSuggestions: String,
    val homeTotalDecksLabel: String,
    val homeTotalDueCardsLabel: String
)

val StringsEn = Strings(
    navHome = "Home",
    navSettings = "Settings",
    navDecks = "Decks",
    navCards = "Cards",
    navBrowse = "Browse",
    navAnalytics = "Analytics",
    settingsTitle = "Settings",
    languageLabel = "Language",
    themeLabel = "Color scheme",
    languageEnglish = "English",
    languageFrench = "French",
    themeLight = "Light",
    themeDark = "Dark",
    homeCreateDeckTitle = "Create a deck",
    homeAiGeneratedTitle = "AI create & import",
    homeAiGeneratedDescription = "Enter a prompt and an amount of cards and see the magic happen.",
    homeAiGeneratedButton = "Create an AI deck",
    homeManualTitle = "Create own cards",
    homeManualDescription = "Make your own flashcards manually.",
    homeManualButton = "Create cards",
    homeImportTitle = "Import deck",
    homeImportDescription = "Paste cards from the clipboard or another source.",
    homeImportButton = "Import cards",
    homeDashboardTitle = "Welcome back",
    homeRecentDeckTitle = "Recent deck",
    homeStatsTitle = "Statistics",
    homeSuggestionsTitle = "Time to review",
    homeNoRecentDeck = "You have not created any decks yet.",
    homeNoSuggestions = "Nothing to review right now.",
    homeTotalDecksLabel = "Total decks",
    homeTotalDueCardsLabel = "Cards due"
)

val StringsFr = Strings(
    navHome = "Accueil",
    navSettings = "Réglages",
    navDecks = "Paquets",
    navCards = "Cartes",
    navBrowse = "Parcourir",
    navAnalytics = "Statistiques",
    settingsTitle = "Réglages",
    languageLabel = "Langue",
    themeLabel = "Schéma de couleurs",
    languageEnglish = "Anglais",
    languageFrench = "Français",
    themeLight = "Clair",
    themeDark = "Sombre",
    homeCreateDeckTitle = "Créer un paquet",
    homeAiGeneratedTitle = "Création et import IA",
    homeAiGeneratedDescription = "Entrez une consigne et un nombre de cartes et laissez la magie opérer.",
    homeAiGeneratedButton = "Créer un paquet IA",
    homeManualTitle = "Créer vos cartes",
    homeManualDescription = "Créez vos propres fiches manuellement.",
    homeManualButton = "Créer des cartes",
    homeImportTitle = "Importer un paquet",
    homeImportDescription = "Collez des cartes depuis le presse-papiers ou une autre source.",
    homeImportButton = "Importer des cartes",
    homeDashboardTitle = "Bon retour",
    homeRecentDeckTitle = "Paquet récent",
    homeStatsTitle = "Statistiques",
    homeSuggestionsTitle = "A revoir",
    homeNoRecentDeck = "Vous n'avez pas encore créé de paquet.",
    homeNoSuggestions = "Rien à réviser pour le moment.",
    homeTotalDecksLabel = "Nombre de paquets",
    homeTotalDueCardsLabel = "Cartes dues"
)

